format_version: 5
pipelines:
  new:
    group:
    materials:
      mygit:
        git: file:///var/go/tmp/infra-as-code/.git/
        branch: master
    stages:
      stage1:
         tasks:
           - exec:
                command: pwd
      stage2:
         tasks:
           - exec:
                command: env
             
