format_version: 5
pipelines:
   new:
      group:
      materials:
         mygit:
           git: file:///tmp/infra-as-code
      stages:
       plan:
         clean_workspace: true
         approval: auto
         jobs:
          TerraPlan:
           tasks:
           -script:
              pwd
              terraform init
              terraform plan
