format_version: 5
pipelines:
  new:
    group:
    materials:
      mygit:
        git: file:///var/go/tmp/infra-as-code/.git/
        branch: master
    stages:
     - build:
         jobs:
           build:
             tasks:
              - exec:
                  command: pwd
      stage2:
       - build1:
          jobs:
            helo: 
              tasks:
               - exec:
                   command: env
             
