format_version: 5
pipelines:
  new:
    group: demo1
    materials:
      mygit:
        git: file:///tmp/infra-as-code/.git/
        branch: master
    stages:
     - build:
         jobs:
           build:
             tasks:
              - exec:
                  command: pwd
                  command1: terraform init
    stage2:
     - build1:
         jobs:
           helo: 
             tasks:
              - exec:
                  command: env
             
