format_version: 5
pipelines:
  new:
    group:
    materials:
      mygit:
        git: file:///var/go/tmp/infra-as-code/.git/
        branch: master
    stages:
     - stage1:
        jobs:
         - job: 
            tasks:
              script:
                command: pwd
