format_version: 5
pipelines:
   new:
      group:
      materials:
         mygit:
           git: file:///tmp/infra-as-code
      stages:
         approval: auto
         jobs:
           tasks:
           -script1:
              terraform init
           -script2:   
              terraform plan
