format_version: 5
pipelines:
   newinstance:
      group:
            materials:
                  mygit:
                    git: file:///projects/infra-as-code
            stages:
               plan:
                  approval: auto
                  jobs:
                      tasks:
                          scripts:
                              terraform init
                              terraform plan
